# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#resources:
#- repo: self
#  clean: true
#  fetchDepth: 1
#queue:
#  name: Hosted VS2017
trigger:
  batch: true
  branches:
    include:
      - master

resources:
- repo: self
  clean: true
  fetchDepth: 1
queue:
  name: Hosted VS2017
steps:
- powershell: ./ build.ps1
  displayName: ScriptBuild
  env:
    NuGetApiKey: $(NuGetApiKey)

